<?php
$cities_data = [
  ['name'=>'Абакан','slug'=>'abakan','cdek_code'=>823,'name_in'=>'в Абакане'],
  ['name'=>'Архангельск','slug'=>'arkhangelsk','cdek_code'=>402,'name_in'=>'в Архангельске'],
  ['name'=>'Астрахань','slug'=>'astrakhan','cdek_code'=>432,'name_in'=>'в Астрахани'],
  ['name'=>'Барнаул','slug'=>'barnaul','cdek_code'=>274,'name_in'=>'в Барнауле'],
  ['name'=>'Белгород','slug'=>'belgorod','cdek_code'=>337,'name_in'=>'в Белгороде'],
  ['name'=>'Брянск','slug'=>'bryansk','cdek_code'=>220,'name_in'=>'в Брянске'],
  ['name'=>'Владивосток','slug'=>'vladivostok','cdek_code'=>288,'name_in'=>'во Владивостоке'],
  ['name'=>'Владикавказ','slug'=>'vladikavkaz','cdek_code'=>1082,'name_in'=>'во Владикавказе'],
  ['name'=>'Владимир','slug'=>'vladimir','cdek_code'=>94,'name_in'=>'во Владимире'],
  ['name'=>'Волгоград','slug'=>'volgograd','cdek_code'=>426,'name_in'=>'в Волгограде'],
  ['name'=>'Вологда','slug'=>'vologda','cdek_code'=>246,'name_in'=>'в Вологде'],
  ['name'=>'Воронеж','slug'=>'voronezh','cdek_code'=>506,'name_in'=>'в Воронеже'],
  ['name'=>'Екатеринбург','slug'=>'ekaterinburg','cdek_code'=>250,'name_in'=>'в Екатеринбурге'],
  ['name'=>'Иваново','slug'=>'ivanovo','cdek_code'=>164,'name_in'=>'в Иваново'],
  ['name'=>'Ижевск','slug'=>'izhevsk','cdek_code'=>224,'name_in'=>'в Ижевске'],
  ['name'=>'Иркутск','slug'=>'irkutsk','cdek_code'=>281,'name_in'=>'в Иркутске'],
  ['name'=>'Йошкар-Ола','slug'=>'yoshkar-ola','cdek_code'=>141,'name_in'=>'в Йошкар-Оле'],
  ['name'=>'Казань','slug'=>'kazan','cdek_code'=>424,'name_in'=>'в Казани'],
  ['name'=>'Калининград','slug'=>'kaliningrad','cdek_code'=>152,'name_in'=>'в Калининграде'],
  ['name'=>'Калуга','slug'=>'kaluga','cdek_code'=>142,'name_in'=>'в Калуге'],
  ['name'=>'Кемерово','slug'=>'kemerovo','cdek_code'=>272,'name_in'=>'в Кемерово'],
  ['name'=>'Киров','slug'=>'kirov','cdek_code'=>415,'name_in'=>'в Кирове'],
  ['name'=>'Кострома','slug'=>'kostroma','cdek_code'=>165,'name_in'=>'в Костроме'],
  ['name'=>'Краснодар','slug'=>'krasnodar','cdek_code'=>435,'name_in'=>'в Краснодаре'],
  ['name'=>'Красноярск','slug'=>'krasnoyarsk','cdek_code'=>278,'name_in'=>'в Красноярске'],
  ['name'=>'Курган','slug'=>'kurgan','cdek_code'=>93,'name_in'=>'в Кургане'],
  ['name'=>'Курск','slug'=>'kursk','cdek_code'=>699,'name_in'=>'в Курске'],
  ['name'=>'Липецк','slug'=>'lipetsk','cdek_code'=>320,'name_in'=>'в Липецке'],
  ['name'=>'Магнитогорск','slug'=>'magnitogorsk','cdek_code'=>258,'name_in'=>'в Магнитогорске'],
  ['name'=>'Махачкала','slug'=>'makhachkala','cdek_code'=>442,'name_in'=>'в Махачкале'],
  ['name'=>'Москва','slug'=>'moskva','cdek_code'=>44,'name_in'=>'в Москве'],
  ['name'=>'Мурманск','slug'=>'murmansk','cdek_code'=>265,'name_in'=>'в Мурманске'],
  ['name'=>'Набережные Челны','slug'=>'naberezhnye-chelny','cdek_code'=>433,'name_in'=>'в Набережных Челнах'],
  ['name'=>'Нальчик','slug'=>'nalchik','cdek_code'=>1081,'name_in'=>'в Нальчике'],
  ['name'=>'Нижневартовск','slug'=>'nizhnevartovsk','cdek_code'=>255,'name_in'=>'в Нижневартовске'],
  ['name'=>'Нижний Новгород','slug'=>'nizhniy-novgorod','cdek_code'=>414,'name_in'=>'в Нижнем Новгороде'],
  ['name'=>'Нижний Тагил','slug'=>'nizhniy-tagil','cdek_code'=>251,'name_in'=>'в Нижнем Тагиле'],
  ['name'=>'Новокузнецк','slug'=>'novokuznetsk','cdek_code'=>273,'name_in'=>'в Новокузнецке'],
  ['name'=>'Новосибирск','slug'=>'novosibirsk','cdek_code'=>270,'name_in'=>'в Новосибирске'],
  ['name'=>'Омск','slug'=>'omsk','cdek_code'=>268,'name_in'=>'в Омске'],
  ['name'=>'Оренбург','slug'=>'orenburg','cdek_code'=>261,'name_in'=>'в Оренбурге'],
  ['name'=>'Орёл','slug'=>'oryol','cdek_code'=>149,'name_in'=>'в Орле'],
  ['name'=>'Пенза','slug'=>'penza','cdek_code'=>504,'name_in'=>'в Пензе'],
  ['name'=>'Пермь','slug'=>'perm','cdek_code'=>248,'name_in'=>'в Перми'],
  ['name'=>'Петрозаводск','slug'=>'petrozavodsk','cdek_code'=>450,'name_in'=>'в Петрозаводске'],
  ['name'=>'Ростов-на-Дону','slug'=>'rostov-na-donu','cdek_code'=>438,'name_in'=>'в Ростове-на-Дону'],
  ['name'=>'Рязань','slug'=>'ryazan','cdek_code'=>159,'name_in'=>'в Рязани'],
  ['name'=>'Самара','slug'=>'samara','cdek_code'=>430,'name_in'=>'в Самаре'],
  ['name'=>'Санкт-Петербург','slug'=>'sankt-peterburg','cdek_code'=>137,'name_in'=>'в Санкт-Петербурге'],
  ['name'=>'Саранск','slug'=>'saransk','cdek_code'=>417,'name_in'=>'в Саранске'],
  ['name'=>'Саратов','slug'=>'saratov','cdek_code'=>428,'name_in'=>'в Саратове'],
  ['name'=>'Смоленск','slug'=>'smolensk','cdek_code'=>395,'name_in'=>'в Смоленске'],
  ['name'=>'Сочи','slug'=>'sochi','cdek_code'=>437,'name_in'=>'в Сочи'],
  ['name'=>'Ставрополь','slug'=>'stavropol','cdek_code'=>439,'name_in'=>'в Ставрополе'],
  ['name'=>'Сургут','slug'=>'surgut','cdek_code'=>254,'name_in'=>'в Сургуте'],
  ['name'=>'Тамбов','slug'=>'tambov','cdek_code'=>298,'name_in'=>'в Тамбове'],
  ['name'=>'Тверь','slug'=>'tver','cdek_code'=>245,'name_in'=>'в Твери'],
  ['name'=>'Тольятти','slug'=>'tolyatti','cdek_code'=>431,'name_in'=>'в Тольятти'],
  ['name'=>'Томск','slug'=>'tomsk','cdek_code'=>269,'name_in'=>'в Томске'],
  ['name'=>'Тула','slug'=>'tula','cdek_code'=>150,'name_in'=>'в Туле'],
  ['name'=>'Тюмень','slug'=>'tyumen','cdek_code'=>252,'name_in'=>'в Тюмени'],
  ['name'=>'Улан-Удэ','slug'=>'ulan-ude','cdek_code'=>230,'name_in'=>'в Улан-Удэ'],
  ['name'=>'Ульяновск','slug'=>'ulyanovsk','cdek_code'=>422,'name_in'=>'в Ульяновске'],
  ['name'=>'Уфа','slug'=>'ufa','cdek_code'=>256,'name_in'=>'в Уфе'],
  ['name'=>'Хабаровск','slug'=>'khabarovsk','cdek_code'=>287,'name_in'=>'в Хабаровске'],
  ['name'=>'Чебоксары','slug'=>'cheboksary','cdek_code'=>419,'name_in'=>'в Чебоксарах'],
  ['name'=>'Челябинск','slug'=>'chelyabinsk','cdek_code'=>259,'name_in'=>'в Челябинске'],
  ['name'=>'Череповец','slug'=>'cherepovets','cdek_code'=>403,'name_in'=>'в Череповце'],
  ['name'=>'Чита','slug'=>'chita','cdek_code'=>231,'name_in'=>'в Чите'],
  ['name'=>'Южно-Сахалинск','slug'=>'yuzhno-sakhalinsk','cdek_code'=>473,'name_in'=>'в Южно-Сахалинске'],
  ['name'=>'Якутск','slug'=>'yakutsk','cdek_code'=>283,'name_in'=>'в Якутске'],
  ['name'=>'Ярославль','slug'=>'yaroslavl','cdek_code'=>146,'name_in'=>'в Ярославле'],
];
usort($cities_data, fn($a,$b) => mb_strtolower($a['name']) <=> mb_strtolower($b['name']));